### ISSUE TITLE
有没有可能集成黑域？

### ISSUE THREAD

**Issue by liudongmiao** [SudaMod/android_frameworks_base#12]
之前 suda 集成过阻止运行补丁。

但是，由于阻止运行不支持 7.0+，我也没有权限发布 阻止运行。
为了快速用上类似功能，目前高度借鉴了最后一个阻止运行的源码版本，开发了新的项目 黑域。
同时，为了便于使用 baksmali/smali 修改补丁，对于 Java 版的补丁进行了一些修改，也就是说，目前补丁不再兼容。

如果愿意支持黑域的话，我就提交下；不愿意的话，请直接关闭此问题，谢谢。

**Comment by ghbhaha** [comment]
可以的 非常感谢

**Comment by ghbhaha** [comment]
https://github.com/SudaMod/android_frameworks_base/commit/976d7c8bd1dd98ad794108d26cb21006a3eafd6f
https://github.com/SudaMod/android_frameworks_base/commit/7f3340911863bc7100201b101e5e3c06d805a2fe
https://github.com/SudaMod/android_frameworks_base/commit/64eebe904cb345792ec5df39c5c116aeec712cca
之前通过这几个补丁 阻止运行能够启动 不知道存在什么问题

**Comment by liudongmiao** [comment]
主要是，黑域换了包名。
而即使7.0把那个api后向移植，也解决不了阻止运行本身不支持7.0的问题。

你大约可以从这个源码里，看到一些更改：
https://github.com/liudongmiao/Brevent/blob/master/assets/patch.py

我晚上提交一下，你们决定看要不要支持。
另外，不建议使用 https://github.com/SudaMod/android_frameworks_base/commit/64eebe904cb345792ec5df39c5c116aeec712cca 这种方式，后向兼容某些应用，理论就应该应用更改。

**Comment by ghbhaha** [comment]
好的
