### ISSUE TITLE
一加一黑屏手势失效

### ISSUE THREAD

**Issue by wuyi-levard** [SudaMod/android_frameworks_base#16]
编译过lineageos和CM都没有问题，不知道是不是三指截屏之类的功能冲突

**Comment by ghbhaha** [comment]
因该不是三指截屏的问题

**Comment by wuyi-levard** [comment]
我看了RR也有三指截屏，对比了代码没有发现问题，同时移除了长按电源键开启手电筒，还是失效，会不会是晃动清理的问题？我找不到其他的原因

**Comment by ghbhaha** [comment]
额 刚准备让你看看是不是手电筒的原因

**Comment by wuyi-levard** [comment]
我昨天试过了，手电筒移除了还是不行

**Comment by ghbhaha** [comment]
我暂时也不清楚了 有段时间我没弄

**Comment by sdhz151** [comment]
合这几样设置没有关系。我自己的源码这几样都有添加，正常

2017年1月1日 上午11:38，"wuyi-ligux" <notifications@github.com>写道：

**Comment by wuyi-levard** [comment]
sdhz151，你也是用一加？我编译的小米4C因为没有黑屏手势，这些也没有问题

**Comment by sdhz151** [comment]
我的是一加二，不是suda的源码，说的是 这几样设置 没有冲突

2017年1月1日 上午11:43，"wuyi-ligux" <notifications@github.com>写道：

**Comment by wuyi-levard** [comment]
那就奇怪了，真不知道那里出的问题

**Comment by ghbhaha** [comment]
https://github.com/SudaMod/android_frameworks_base/blob/sm-3.0/services/core/java/com/android/server/policy/PhoneWindowManager.java 把这个换成初始的试试

**Comment by wuyi-levard** [comment]
恩，昨天已经试过把这个里面的手电筒屏蔽了，今天彻底屏蔽掉试试

**Comment by wuyi-levard** [comment]
加了T9最好把contactsprovider的hanzi2pinyin也更新一下，使用自己的源吧

**Comment by ghbhaha** [comment]
邀请你了 你帮忙改下吧  出去有事了

**Comment by wuyi-levard** [comment]
好的

**Comment by wuyi-levard** [comment]
对了，短信的issues你没开，现在有个bug，不管归档是不是开启的，所有短信都会自动归档，有空要修复一下

**Comment by ghbhaha** [comment]
我没发现啊

**Comment by wuyi-levard** [comment]
我这里有人反馈，我也试了一下，我的开关都是关闭的，收到短信就自动归档进去了，进入短信界面是空的

**Comment by wuyi-levard** [comment]
换成初始的还是没用。。。。看来不是这里的问题，我再试试其他的

**Comment by sdhz151** [comment]
是不是 光 手电筒 失效  黑屏手势 相机正常

2017年1月1日 下午5:03，"wuyi-ligux" <notifications@github.com>写道：

**Comment by sdhz151** [comment]
packages/SystemUI/res/values/config.xml

<bool name="config_useWakelockForFlashlight">false</bool>

改成
<bool name="config_useWakelockForFlashlight">true</bool>

回着在
device/oneplus/./overlay/frameworks/base/packages/SystemUI/res/values/config.xml

添加
<bool name="config_useWakelockForFlashlight">true</bool>
看看可以不

2017年1月2日 下午12:16，"，杨辉" <yanghui140@gmail.com>写道：

**Comment by wuyi-levard** [comment]
不是，是整个黑屏手势，除了双击唤醒，全部失效，比如画圈开相机，画V开手电，控制音乐，整个附加设置都废了

**Comment by sdhz151** [comment]
哦 那就不知道了

2017年1月2日 下午1:31，"wuyi-ligux" <notifications@github.com>写道：

**Comment by wuyi-levard** [comment]
我现在把整个SUDA添加的手势都还原了，试试看还会不会失效，如果不会，那就是这里的问题了

**Comment by YumeMichi** [comment]
姑且看看logcat能捕捉到黑屏手势事件

**Comment by wuyi-levard** [comment]
01-02 13:56:42.880  2513  2814 I PowerManagerService: Waking up from sleep (uid 1000)...
01-02 13:56:42.881  2513  2513 V KeyguardServiceDelegate: onStartedWakingUp()
01-02 13:56:42.887  3031  3031 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
01-02 13:56:42.893  2513  2582 I DisplayPowerController: Blocking screen on until initial contents have been drawn.
01-02 13:56:42.894  2513  2582 V KeyguardServiceDelegate: onScreenTurnedOn(showListener = com.android.server.policy.PhoneWindowManager$2@79881d8)
01-02 13:56:42.894  2513  2582 I qti_sensors_hal: TMG-3993 Ambient: batch   4.00    inf
01-02 13:56:42.897  2513  2582 I qti_sensors_hal: TMG-3993 Ambient: activate=1
01-02 13:56:42.901  2513  2814 I QCOM PowerHAL: Got set_interactive hint
01-02 13:56:42.903  2513  2962 D Prevent : screen on
01-02 13:56:42.906   271  8058 D audio_hw_primary: adev_set_parameters: enter: screen_state=on
01-02 13:56:42.910  2513  2580 I DisplayManagerService: Display device changed state: "内置屏幕", ON
01-02 13:56:42.912  2513  4142 I qti_sensors_hal: TMG-3993 IR_Gesture  & Proximity: batch  50.00    inf
01-02 13:56:42.912  2513  4142 I qti_sensors_hal: TMG-3993 IR_Gesture  & Proximity: activate=1
01-02 13:56:42.912   255   255 D SurfaceFlinger: Set power mode=2, type=0 flinger=0xb6832000
01-02 13:56:42.912   255   255 D qdhwcomposer: hwc_setPowerMode: Setting mode 2 on display: 0
01-02 13:56:42.930  2513  2644 V KeyguardServiceDelegate: **** SHOWN CALLED ****
01-02 13:56:42.986  2513  2582 I DisplayPowerController: Unblocked screen on after 93 ms
01-02 13:56:42.986  2513  2582 V KeyguardServiceDelegate: onScreenTurnedOn()
01-02 13:56:43.143  4049  4237 D BrcmNfcJni: RoutingManager::nfaEeCallback: NFA_EE_SET_TECH_CFG_EVT; status=0x0
01-02 13:56:43.144  4049  4237 D BrcmNfcJni: RoutingManager::nfaEeCallback: NFA_EE_SET_PROTO_CFG_EVT; status=0x0
01-02 13:56:43.144  4049 25009 D BrcmNfcJni: RoutingManager::commitRouting
01-02 13:56:43.144  4049  4237 D BrcmNfcJni: RoutingManager::nfaEeCallback: NFA_EE_UPDATED_EVT
01-02 13:56:43.145  4049  4245 E NxpTml  : _i2c_write() errno : 5
01-02 13:56:43.145  4049  4245 E NxpTml  : PN54X - Error in I2C Write.....
01-02 13:56:43.145  4049  4247 E NxpHal  : write error status = 0x1ff
01-02 13:56:43.145  4049  4237 E NxpHal  : write_unlocked failed - PN54X Maybe in Standby Mode - Retry
01-02 13:56:43.181   255   384 I qdhwcomposer: handle_blank_event: dpy:0 panel power state: 1
01-02 13:56:43.183   255   255 D qdhwcomposer: hwc_setPowerMode: Done setting mode 2 on display 0
01-02 13:56:43.184  2513  2979 D SurfaceControl: Excessive delay in setPowerMode(): 274ms
01-02 13:56:44.469  2513  2814 I PowerManagerService: Going to sleep due to power button (uid 1000)...
01-02 13:56:44.477  3031  3031 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
01-02 13:56:44.481  2513  2582 W Adreno-EGL: <qeglDrvAPI_eglQueryContext:4370>: EGL_BAD_ATTRIBUTE
01-02 13:56:44.953  2513  2582 V KeyguardServiceDelegate: onScreenTurnedOff()
01-02 13:56:44.956  2513  3449 I qti_sensors_hal: TMG-3993 IR_Gesture  & Proximity: activate=0
01-02 13:56:44.972  2513  2582 I qti_sensors_hal: TMG-3993 Ambient: activate=0
01-02 13:56:44.978  2513  2580 I DisplayManagerService: Display device changed state: "内置屏幕", OFF
01-02 13:56:44.981   255   255 D SurfaceFlinger: Set power mode=0, type=0 flinger=0xb6832000
01-02 13:56:44.981   255   255 D qdhwcomposer: hwc_setPowerMode: Setting mode 0 on display: 0
01-02 13:56:45.200   255   384 I qdhwcomposer: handle_blank_event: dpy:0 panel power state: 0
01-02 13:56:45.206   255   255 D qdhwcomposer: hwc_setPowerMode: Done setting mode 0 on display 0
01-02 13:56:45.206  2513  2979 D SurfaceControl: Excessive delay in setPowerMode(): 228ms
01-02 13:56:45.209  2513  2582 I QCOM PowerHAL: Got set_interactive hint
01-02 13:56:45.214  2513  2582 I PowerManagerService: Sleeping (uid 1000)...
01-02 13:56:45.229  2513  2962 D Prevent : screen off
01-02 13:56:45.237  3031  3031 D PhoneStatusBar: disable: < expand ICONS alerts SYSTEM_INFO back HOME RECENT clock SEARCH quick_settings >
01-02 13:56:45.241  3031  3031 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
01-02 13:56:45.245  3031  3031 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
01-02 13:56:45.247   271   558 D audio_hw_primary: adev_set_parameters: enter: screen_state=off
01-02 13:56:45.247  3031  3031 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
01-02 13:56:45.252  3024  3024 I GoogleInputMethod: onReceive() : Action = android.intent.action.SCREEN_OFF
01-02 13:56:45.281  4049  4245 E NxpTml  : _i2c_write() errno : 5
01-02 13:56:45.281  4049  4245 E NxpTml  : PN54X - Error in I2C Write.....
01-02 13:56:45.281  4049  4247 E NxpHal  : write error status = 0x1ff
01-02 13:56:45.281  4049  4237 E NxpHal  : write_unlocked failed - PN54X Maybe in Standby Mode - Retry

**Comment by wuyi-levard** [comment]
黑屏下手势完全没有log

**Comment by wuyi-levard** [comment]
还原了所有手势，还是不行。。。。汗！！！

**Comment by YumeMichi** [comment]
我拿X编译一个试试看 很久没用SudaMod了正好要弄AOSP顺便一起 _(:з」∠)_

**Comment by wuyi-levard** [comment]
X和1配置基本一样，不知道你的会不会出问题

**Comment by YumeMichi** [comment]
真有一样的问题 而且我连三段式都无效了

**Comment by ghbhaha** [comment]
我看了下 com.cyanogenmod.keyhandler.jar这个jar没有生成

**Comment by YumeMichi** [comment]
看了一下我这里有生成这个文件
![](https://blog.ikke.moe/images/sm.png)

**Comment by ghbhaha** [comment]
https://github.com/SudaMod/android_frameworks_base/blob/sm-3.0/services/core/java/com/android/server/policy/PhoneWindowManager.java     把debug设成true再看看有没有相关日志呢 ，暂时也不清楚了

**Comment by YumeMichi** [comment]
logcat 手势和三段式
```
01-02 17:34:02.793  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:02.794  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:04.857  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:04.857  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:05.811  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:05.811  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:20.312  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:20.316  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:21.583  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:21.584  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:22.295  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:22.298  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.190  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.193  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.214  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.215  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.588  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
01-02 17:34:23.589  1727  3225 D WindowManager: interceptKeyTq keycode=0 interactive=false keyguardActive=true policyFlags=2000000
```

**Comment by wuyi-levard** [comment]
我测试过lineage，是没有问题的，现在还原代码一大半了，剩下后台锁和状态栏的代码没有还原，可以排除其他的可能

**Comment by sdhz151** [comment]
先还原cm_platform_sdk看看

2017年1月2日 下午5:53，"wuyi-ligux" <notifications@github.com>写道：

**Comment by wuyi-levard** [comment]
试过了，还是不行

**Comment by wuyi-levard** [comment]
后台锁排除

**Comment by wuyi-levard** [comment]
整个base都还原了，现在不调用sudasdk试试。。。。

**Comment by ghbhaha** [comment]
真够有毅力

**Comment by wuyi-levard** [comment]
欲哭无泪

**Comment by wuyi-levard** [comment]
没黑屏开手电真不习惯

**Comment by ghbhaha** [comment]
加qq吧 这里太不方便了

**Comment by wuyi-levard** [comment]
58865341，你加我吧

**Comment by ghbhaha** [comment]
https://github.com/SudaMod-devices/android_device_oppo_common/commit/30ad5c42613380d83428fa950025193655a6f617 把hasSetupCompleted()默认返回true就行，开机引导被我去掉了

**Comment by wuyi-levard** [comment]
原来是这个。。。。SM没编译开机引导app。。。。夭寿

**Comment by YumeMichi** [comment]
_(:з」∠)_
